@startuml

package "Car Rental System" {

  package "Car Rental System Interfaces" as Interfaces {
    rectangle "Interface classes"
  }

  package "Car Rental System Entities" as Entities {
    rectangle Customer
    rectangle "Car" as Car
    rectangle "Rental" as Rental
  }

  package "Car Rental System Aspects" as Aspects{
    rectangle "Authentication"
    rectangle "Security"
    rectangle "Data Persistence"
    rectangle "Error Handler"
    rectangle "Message Handler"
    rectangle "Data Persistence"
  }

  package "Car Rental System Controller" as Controller {
    rectangle "CarRentalSystem" 
    rectangle "CarRentalContext"
    rectangle "CarRentalCommands"
  }

  package "Car Rental System Main Program" as Main {
    rectangle "MainProgram" as MainProgram
  }

  Main -down-> Controller

  Controller -right-> Aspects
  Controller -down-> Entities

  Aspects -down-> Entities

  Controller -left-> Interfaces
  Entities -up-> Interfaces
  
  Aspects -> Interfaces
}
@enduml